CREATE TABLE Owner_Info(
ONo CHAR(6) NOT NULL CONSTRAINT O_Prim PRIMARY KEY,
OName CHAR(8) NOT NULL,
OSex NCHAR(2) NOT NULL,
OTel CHAR(13) NOT NULL,
OID CHAR(18) NOT NULL,
ONote CHAR(100))

CREATE TABLE House_Info(
HNo CHAR(12) NOT NULL CONSTRAINT H_Prim PRIMARY KEY,
HBuild INT NOT NULL,
HPark INT NOT NULL,
HFloor INT NOT NULL,
HRoom INT NOT NULL,
HArea INT NOT NULL,
HState CHAR(6) NOT NULL,
HType CHAR(8) NOT NULL,
HNote CHAR(100),
ONo CHAR(6) CONSTRAINT O_Fore FOREIGN KEY REFERENCES Owner_Info(ONo))

USE Sql_Curriculum_Design
GO
CREATE TRIGGER del_H ON House_Info
AFTER DELETE
AS
	DELETE FROM Owner_Info
	WHERE Owner_Info.ONo
	IN (SELECT ONo FROM DELETED)
GO

USE Sql_Curriculum_Design
GO
CREATE TRIGGER Update_O ON Owner_Info
FOR UPDATE
AS
	IF UPDATE(ONo)
	UPDATE House_Info SET ONo=inserted.ONo
	FROM House_Info,deleted,inserted
	WHERE House_Info.ONo=deleted.ONo
GO